"""Builtin module definitions for YARA type system."""

from __future__ import annotations

from typing import Any

from yaraast.types._registry_base import YaraType
from yaraast.types.module_contracts import FunctionDefinition, ModuleDefinition

# Declarative module specs: type strings -> actual types resolved at load time.
# "i"=int, "s"=str, "b"=bool, "d"=double
# Compound: ("array", elem), ("dict", k, v), ("struct", {fields})
# Functions: (return_type, [(param_name, param_type), ...], min_parameters?, variadic?)

_MODULE_SPECS: dict[str, dict[str, Any]] = {
    "pe": {
        "consts": {
            "IMAGE_DIRECTORY_ENTRY_COPYRIGHT": "i",
            "IMAGE_NT_OPTIONAL_HDR32_MAGIC": "i",
            "IMAGE_NT_OPTIONAL_HDR64_MAGIC": "i",
            "IMAGE_ROM_OPTIONAL_HDR_MAGIC": "i",
            "SECTION_SCALE_INDEX": "i",
            "IMAGE_DEBUG_TYPE_UNKNOWN": "i",
            "IMAGE_DEBUG_TYPE_COFF": "i",
            "IMAGE_DEBUG_TYPE_CODEVIEW": "i",
            "IMAGE_DEBUG_TYPE_FPO": "i",
            "IMAGE_DEBUG_TYPE_MISC": "i",
            "IMAGE_DEBUG_TYPE_EXCEPTION": "i",
            "IMAGE_DEBUG_TYPE_FIXUP": "i",
            "IMAGE_DEBUG_TYPE_OMAP_TO_SRC": "i",
            "IMAGE_DEBUG_TYPE_OMAP_FROM_SRC": "i",
            "IMAGE_DEBUG_TYPE_BORLAND": "i",
            "IMAGE_DEBUG_TYPE_RESERVED10": "i",
            "IMAGE_DEBUG_TYPE_CLSID": "i",
            "IMAGE_DEBUG_TYPE_VC_FEATURE": "i",
            "IMAGE_DEBUG_TYPE_POGO": "i",
            "IMAGE_DEBUG_TYPE_ILTCG": "i",
            "IMAGE_DEBUG_TYPE_MPX": "i",
            "IMAGE_DEBUG_TYPE_REPRO": "i",
            "MACHINE_UNKNOWN": "i",
            "MACHINE_AM33": "i",
            "MACHINE_AMD64": "i",
            "MACHINE_ARM": "i",
            "MACHINE_ARM64": "i",
            "MACHINE_ARMNT": "i",
            "MACHINE_EBC": "i",
            "MACHINE_I386": "i",
            "MACHINE_IA64": "i",
            "MACHINE_M32R": "i",
            "MACHINE_MIPS16": "i",
            "MACHINE_MIPSFPU": "i",
            "MACHINE_MIPSFPU16": "i",
            "MACHINE_POWERPC": "i",
            "MACHINE_POWERPCFP": "i",
            "MACHINE_R4000": "i",
            "MACHINE_SH3": "i",
            "MACHINE_SH3DSP": "i",
            "MACHINE_SH4": "i",
            "MACHINE_SH5": "i",
            "MACHINE_THUMB": "i",
            "MACHINE_WCEMIPSV2": "i",
            "MACHINE_TARGET_HOST": "i",
            "MACHINE_R3000": "i",
            "MACHINE_R10000": "i",
            "MACHINE_ALPHA": "i",
            "MACHINE_SH3E": "i",
            "MACHINE_ALPHA64": "i",
            "MACHINE_AXP64": "i",
            "MACHINE_TRICORE": "i",
            "MACHINE_CEF": "i",
            "MACHINE_CEE": "i",
            "SUBSYSTEM_UNKNOWN": "i",
            "SUBSYSTEM_NATIVE": "i",
            "SUBSYSTEM_WINDOWS_GUI": "i",
            "SUBSYSTEM_WINDOWS_CUI": "i",
            "SUBSYSTEM_OS2_CUI": "i",
            "SUBSYSTEM_POSIX_CUI": "i",
            "SUBSYSTEM_NATIVE_WINDOWS": "i",
            "SUBSYSTEM_WINDOWS_CE_GUI": "i",
            "SUBSYSTEM_EFI_APPLICATION": "i",
            "SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER": "i",
            "SUBSYSTEM_EFI_RUNTIME_DRIVER": "i",
            "SUBSYSTEM_EFI_ROM_IMAGE": "i",
            "SUBSYSTEM_XBOX": "i",
            "SUBSYSTEM_WINDOWS_BOOT_APPLICATION": "i",
            "RELOCS_STRIPPED": "i",
            "EXECUTABLE_IMAGE": "i",
            "LINE_NUMS_STRIPPED": "i",
            "LOCAL_SYMS_STRIPPED": "i",
            "AGGRESIVE_WS_TRIM": "i",
            "LARGE_ADDRESS_AWARE": "i",
            "BYTES_REVERSED_LO": "i",
            "MACHINE_32BIT": "i",
            "DEBUG_STRIPPED": "i",
            "REMOVABLE_RUN_FROM_SWAP": "i",
            "NET_RUN_FROM_SWAP": "i",
            "SYSTEM": "i",
            "DLL": "i",
            "UP_SYSTEM_ONLY": "i",
            "BYTES_REVERSED_HI": "i",
            "IMAGE_DIRECTORY_ENTRY_EXPORT": "i",
            "IMAGE_DIRECTORY_ENTRY_IMPORT": "i",
            "IMAGE_DIRECTORY_ENTRY_RESOURCE": "i",
            "IMAGE_DIRECTORY_ENTRY_EXCEPTION": "i",
            "IMAGE_DIRECTORY_ENTRY_SECURITY": "i",
            "IMAGE_DIRECTORY_ENTRY_BASERELOC": "i",
            "IMAGE_DIRECTORY_ENTRY_DEBUG": "i",
            "IMAGE_DIRECTORY_ENTRY_ARCHITECTURE": "i",
            "IMAGE_DIRECTORY_ENTRY_GLOBALPTR": "i",
            "IMAGE_DIRECTORY_ENTRY_TLS": "i",
            "IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG": "i",
            "IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT": "i",
            "IMAGE_DIRECTORY_ENTRY_IAT": "i",
            "IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT": "i",
            "IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR": "i",
            "SECTION_NO_PAD": "i",
            "SECTION_CNT_CODE": "i",
            "SECTION_CNT_INITIALIZED_DATA": "i",
            "SECTION_CNT_UNINITIALIZED_DATA": "i",
            "SECTION_LNK_OTHER": "i",
            "SECTION_LNK_INFO": "i",
            "SECTION_LNK_REMOVE": "i",
            "SECTION_LNK_COMDAT": "i",
            "SECTION_NO_DEFER_SPEC_EXC": "i",
            "SECTION_GPREL": "i",
            "SECTION_MEM_FARDATA": "i",
            "SECTION_MEM_PURGEABLE": "i",
            "SECTION_MEM_16BIT": "i",
            "SECTION_MEM_LOCKED": "i",
            "SECTION_MEM_PRELOAD": "i",
            "SECTION_ALIGN_1BYTES": "i",
            "SECTION_ALIGN_2BYTES": "i",
            "SECTION_ALIGN_4BYTES": "i",
            "SECTION_ALIGN_8BYTES": "i",
            "SECTION_ALIGN_16BYTES": "i",
            "SECTION_ALIGN_32BYTES": "i",
            "SECTION_ALIGN_64BYTES": "i",
            "SECTION_ALIGN_128BYTES": "i",
            "SECTION_ALIGN_256BYTES": "i",
            "SECTION_ALIGN_512BYTES": "i",
            "SECTION_ALIGN_1024BYTES": "i",
            "SECTION_ALIGN_2048BYTES": "i",
            "SECTION_ALIGN_4096BYTES": "i",
            "SECTION_ALIGN_8192BYTES": "i",
            "SECTION_ALIGN_MASK": "i",
            "SECTION_LNK_NRELOC_OVFL": "i",
            "SECTION_MEM_DISCARDABLE": "i",
            "SECTION_MEM_NOT_CACHED": "i",
            "SECTION_MEM_NOT_PAGED": "i",
            "SECTION_MEM_SHARED": "i",
            "SECTION_MEM_EXECUTE": "i",
            "SECTION_MEM_READ": "i",
            "SECTION_MEM_WRITE": "i",
            "RESOURCE_TYPE_CURSOR": "i",
            "RESOURCE_TYPE_BITMAP": "i",
            "RESOURCE_TYPE_ICON": "i",
            "RESOURCE_TYPE_MENU": "i",
            "RESOURCE_TYPE_DIALOG": "i",
            "RESOURCE_TYPE_STRING": "i",
            "RESOURCE_TYPE_FONTDIR": "i",
            "RESOURCE_TYPE_FONT": "i",
            "RESOURCE_TYPE_ACCELERATOR": "i",
            "RESOURCE_TYPE_RCDATA": "i",
            "RESOURCE_TYPE_MESSAGETABLE": "i",
            "RESOURCE_TYPE_GROUP_CURSOR": "i",
            "RESOURCE_TYPE_GROUP_ICON": "i",
            "RESOURCE_TYPE_VERSION": "i",
            "RESOURCE_TYPE_DLGINCLUDE": "i",
            "RESOURCE_TYPE_PLUGPLAY": "i",
            "RESOURCE_TYPE_VXD": "i",
            "RESOURCE_TYPE_ANICURSOR": "i",
            "RESOURCE_TYPE_ANIICON": "i",
            "RESOURCE_TYPE_HTML": "i",
            "RESOURCE_TYPE_MANIFEST": "i",
            "IMPORT_DELAYED": "i",
            "IMPORT_STANDARD": "i",
            "IMPORT_ANY": "i",
            "HIGH_ENTROPY_VA": "i",
            "DYNAMIC_BASE": "i",
            "FORCE_INTEGRITY": "i",
            "NX_COMPAT": "i",
            "NO_ISOLATION": "i",
            "NO_SEH": "i",
            "NO_BIND": "i",
            "APPCONTAINER": "i",
            "WDM_DRIVER": "i",
            "GUARD_CF": "i",
            "TERMINAL_SERVER_AWARE": "i",
        },
        "attrs": {
            "machine": "i",
            "subsystem": "i",
            "checksum": "i",
            "number_of_sections": "i",
            "timestamp": "i",
            "characteristics": "i",
            "dll_characteristics": "i",
            "entry_point": "i",
            "entry_point_raw": "i",
            "image_base": "i",
            "base_of_code": "i",
            "base_of_data": "i",
            "size_of_image": "i",
            "size_of_code": "i",
            "size_of_initialized_data": "i",
            "size_of_uninitialized_data": "i",
            "size_of_headers": "i",
            "size_of_optional_header": "i",
            "size_of_stack_reserve": "i",
            "size_of_stack_commit": "i",
            "size_of_heap_reserve": "i",
            "size_of_heap_commit": "i",
            "opthdr_magic": "i",
            "win32_version_value": "i",
            "loader_flags": "i",
            "file_alignment": "i",
            "section_alignment": "i",
            "pointer_to_symbol_table": "i",
            "number_of_symbols": "i",
            "pdb_path": "s",
            "dll_name": "s",
            "export_timestamp": "i",
            "number_of_imports": "i",
            "number_of_imported_functions": "i",
            "number_of_delayed_imports": "i",
            "number_of_delayed_imported_functions": "i",
            "number_of_exports": "i",
            "number_of_exported_functions": "i",
            "number_of_version_infos": "i",
            "linker_version": (
                "struct",
                {"major": "i", "minor": "i"},
            ),
            "os_version": (
                "struct",
                {"major": "i", "minor": "i"},
            ),
            "image_version": (
                "struct",
                {"major": "i", "minor": "i"},
            ),
            "subsystem_version": (
                "struct",
                {"major": "i", "minor": "i"},
            ),
            "data_directories": (
                "array",
                (
                    "struct",
                    {
                        "virtual_address": "i",
                        "size": "i",
                    },
                ),
            ),
            "resources": (
                "array",
                (
                    "struct",
                    {
                        "rva": "i",
                        "offset": "i",
                        "length": "i",
                        "type": "i",
                        "id": "i",
                        "language": "i",
                        "type_string": "s",
                        "name_string": "s",
                        "language_string": "s",
                    },
                ),
            ),
            "version_info_list": (
                "array",
                (
                    "struct",
                    {
                        "key": "s",
                        "value": "s",
                    },
                ),
            ),
            "sections": (
                "array",
                (
                    "struct",
                    {
                        "name": "s",
                        "full_name": "s",
                        "virtual_address": "i",
                        "virtual_size": "i",
                        "raw_data_offset": "i",
                        "raw_data_size": "i",
                        "pointer_to_relocations": "i",
                        "pointer_to_line_numbers": "i",
                        "number_of_relocations": "i",
                        "number_of_line_numbers": "i",
                        "characteristics": "i",
                    },
                ),
            ),
            "overlay": (
                "struct",
                {
                    "offset": "i",
                    "size": "i",
                },
            ),
            "rich_signature": (
                "struct",
                {
                    "offset": "i",
                    "length": "i",
                    "clear_data": "s",
                    "key": "i",
                    "raw_data": "s",
                },
            ),
            "version_info": ("dict", "s", "s"),
            "number_of_resources": "i",
            "resource_timestamp": "i",
            "number_of_signatures": "i",
            "signatures": (
                "array",
                (
                    "struct",
                    {
                        "issuer": "s",
                        "subject": "s",
                        "serial": "s",
                        "thumbprint": "s",
                        "version": "i",
                        "not_before": "i",
                        "not_after": "i",
                        "digest_alg": "s",
                        "file_digest": "s",
                        "number_of_certificates": "i",
                        "certificates": (
                            "array",
                            (
                                "struct",
                                {
                                    "issuer": "s",
                                    "subject": "s",
                                    "serial": "s",
                                    "thumbprint": "s",
                                    "version": "i",
                                    "not_before": "i",
                                    "not_after": "i",
                                },
                            ),
                        ),
                    },
                ),
            ),
            "is_pe": "b",
        },
        "funcs": {
            "imphash": ("s", []),
            "section_index": ("i", [("name_or_offset", "scalar")]),
            "exports": ("b", [("name_or_ordinal", "scalar")]),
            "imports": (
                "b",
                [
                    ("dll_or_descriptor", "scalar"),
                    ("function_or_ordinal", "scalar"),
                    ("function_or_ordinal", "scalar"),
                ],
                1,
            ),
            "locale": ("b", [("locale", "i")]),
            "language": ("b", [("lang", "i")]),
            "is_dll": ("b", []),
            "is_64bit": ("b", []),
            "is_32bit": ("b", []),
            "calculate_checksum": ("i", []),
            "rva_to_offset": ("i", [("rva", "i")]),
            "rich_signature.version": ("i", [("toolid", "i"), ("version", "i")], 1),
            "rich_signature.toolid": ("i", [("toolid", "i"), ("version", "i")], 1),
        },
    },
    "math": {
        "consts": {
            "MEAN_BYTES": "d",
        },
        "funcs": {
            "abs": ("i", [("x", "i")]),
            "min": ("i", [("a", "i"), ("b", "i")]),
            "max": ("i", [("a", "i"), ("b", "i")]),
            "to_string": ("s", [("n", "i"), ("base", "i")], 1),
            "to_number": ("i", [("b", "b")]),
            "entropy": ("d", [("value_or_offset", "s"), ("size", "i")], 1),
            "mean": ("d", [("value_or_offset", "s"), ("size", "i")], 1),
            "deviation": ("d", [("value_or_offset", "s"), ("size_or_mean", "d"), ("mean", "d")], 2),
            "serial_correlation": ("d", [("value_or_offset", "s"), ("size", "i")], 1),
            "monte_carlo_pi": ("d", [("value_or_offset", "s"), ("size", "i")], 1),
            "count": ("i", [("byte", "i"), ("offset", "i"), ("size", "i")], 1),
            "percentage": ("d", [("byte", "i"), ("offset", "i"), ("size", "i")], 1),
            "mode": ("i", [("offset", "i"), ("size", "i")], 0),
            "in_range": ("b", [("test", "d"), ("lower", "d"), ("upper", "d")]),
        },
    },
    "elf": {
        "consts": {
            "ET_NONE": "i",
            "ET_REL": "i",
            "ET_EXEC": "i",
            "ET_DYN": "i",
            "ET_CORE": "i",
            "EM_NONE": "i",
            "EM_M32": "i",
            "EM_SPARC": "i",
            "EM_386": "i",
            "EM_68K": "i",
            "EM_88K": "i",
            "EM_860": "i",
            "EM_MIPS": "i",
            "EM_MIPS_RS3_LE": "i",
            "EM_PPC": "i",
            "EM_PPC64": "i",
            "EM_ARM": "i",
            "EM_X86_64": "i",
            "EM_AARCH64": "i",
            "SHT_NULL": "i",
            "SHT_PROGBITS": "i",
            "SHT_SYMTAB": "i",
            "SHT_STRTAB": "i",
            "SHT_RELA": "i",
            "SHT_HASH": "i",
            "SHT_DYNAMIC": "i",
            "SHT_NOTE": "i",
            "SHT_NOBITS": "i",
            "SHT_REL": "i",
            "SHT_SHLIB": "i",
            "SHT_DYNSYM": "i",
            "SHF_WRITE": "i",
            "SHF_ALLOC": "i",
            "SHF_EXECINSTR": "i",
            "PT_NULL": "i",
            "PT_LOAD": "i",
            "PT_DYNAMIC": "i",
            "PT_INTERP": "i",
            "PT_NOTE": "i",
            "PT_SHLIB": "i",
            "PT_PHDR": "i",
            "PT_TLS": "i",
            "PT_GNU_EH_FRAME": "i",
            "PT_GNU_STACK": "i",
            "DT_NULL": "i",
            "DT_NEEDED": "i",
            "DT_PLTRELSZ": "i",
            "DT_PLTGOT": "i",
            "DT_HASH": "i",
            "DT_STRTAB": "i",
            "DT_SYMTAB": "i",
            "DT_RELA": "i",
            "DT_RELASZ": "i",
            "DT_RELAENT": "i",
            "DT_STRSZ": "i",
            "DT_SYMENT": "i",
            "DT_INIT": "i",
            "DT_FINI": "i",
            "DT_SONAME": "i",
            "DT_RPATH": "i",
            "DT_SYMBOLIC": "i",
            "DT_REL": "i",
            "DT_RELSZ": "i",
            "DT_RELENT": "i",
            "DT_PLTREL": "i",
            "DT_DEBUG": "i",
            "DT_TEXTREL": "i",
            "DT_JMPREL": "i",
            "DT_BIND_NOW": "i",
            "DT_INIT_ARRAY": "i",
            "DT_FINI_ARRAY": "i",
            "DT_INIT_ARRAYSZ": "i",
            "DT_FINI_ARRAYSZ": "i",
            "DT_RUNPATH": "i",
            "DT_FLAGS": "i",
            "DT_ENCODING": "i",
            "STT_NOTYPE": "i",
            "STT_OBJECT": "i",
            "STT_FUNC": "i",
            "STT_SECTION": "i",
            "STT_FILE": "i",
            "STT_COMMON": "i",
            "STT_TLS": "i",
            "STB_LOCAL": "i",
            "STB_GLOBAL": "i",
            "STB_WEAK": "i",
            "PF_X": "i",
            "PF_W": "i",
            "PF_R": "i",
        },
        "attrs": {
            "type": "i",
            "machine": "i",
            "entry_point": "i",
            "sh_offset": "i",
            "sh_entry_size": "i",
            "ph_offset": "i",
            "ph_entry_size": "i",
            "number_of_sections": "i",
            "number_of_segments": "i",
            "number_of_symbols": "i",
            "symtab_entries": "i",
            "dynsym_entries": "i",
            "dynamic_section_entries": "i",
            "sections": (
                "array",
                (
                    "struct",
                    {
                        "name": "s",
                        "type": "i",
                        "flags": "i",
                        "address": "i",
                        "size": "i",
                        "offset": "i",
                    },
                ),
            ),
            "segments": (
                "array",
                (
                    "struct",
                    {
                        "type": "i",
                        "flags": "i",
                        "offset": "i",
                        "virtual_address": "i",
                        "physical_address": "i",
                        "file_size": "i",
                        "memory_size": "i",
                        "alignment": "i",
                    },
                ),
            ),
            "symtab": (
                "array",
                (
                    "struct",
                    {
                        "name": "s",
                        "value": "i",
                        "size": "i",
                        "type": "i",
                        "bind": "i",
                        "shndx": "i",
                    },
                ),
            ),
            "dynsym": (
                "array",
                (
                    "struct",
                    {
                        "name": "s",
                        "value": "i",
                        "size": "i",
                        "type": "i",
                        "bind": "i",
                        "shndx": "i",
                    },
                ),
            ),
            "dynamic": (
                "array",
                (
                    "struct",
                    {
                        "type": "i",
                        "val": "i",
                    },
                ),
            ),
        },
    },
    "hash": {
        "funcs": {
            "md5": ("s", [("value_or_offset", "s"), ("size", "i")], 1),
            "sha1": ("s", [("value_or_offset", "s"), ("size", "i")], 1),
            "sha256": ("s", [("value_or_offset", "s"), ("size", "i")], 1),
            "checksum32": ("i", [("value_or_offset", "s"), ("size", "i")], 1),
            "crc32": ("i", [("value_or_offset", "s"), ("size", "i")], 1),
        },
    },
    "dotnet": {
        "attrs": {
            "is_dotnet": "i",
            "version": "s",
            "module_name": "s",
            "typelib": "s",
            "number_of_streams": "i",
            "number_of_guids": "i",
            "number_of_resources": "i",
            "number_of_user_strings": "i",
            "number_of_assembly_refs": "i",
            "number_of_modulerefs": "i",
            "number_of_classes": "i",
            "number_of_field_offsets": "i",
            "number_of_constants": "i",
            "number_of_memberrefs": "i",
            "field_offsets": ("array", "i"),
            "constants": ("array", "s"),
            "modulerefs": ("array", "s"),
            "memberrefs": (
                "array",
                ("struct", {"name": "s"}),
            ),
            "classes": (
                "array",
                (
                    "struct",
                    {
                        "fullname": "s",
                        "name": "s",
                        "namespace": "s",
                        "visibility": "s",
                        "type": "s",
                        "abstract": "i",
                        "sealed": "i",
                        "number_of_generic_parameters": "i",
                        "generic_parameters": ("array", "s"),
                        "number_of_base_types": "i",
                        "base_types": ("array", "s"),
                        "number_of_methods": "i",
                        "methods": (
                            "array",
                            (
                                "struct",
                                {
                                    "name": "s",
                                    "visibility": "s",
                                    "abstract": "i",
                                    "static": "i",
                                    "virtual": "i",
                                    "final": "i",
                                    "return_type": "s",
                                    "number_of_generic_parameters": "i",
                                    "generic_parameters": ("array", "s"),
                                    "number_of_parameters": "i",
                                    "parameters": (
                                        "array",
                                        ("struct", {"name": "s", "type": "s"}),
                                    ),
                                },
                            ),
                        ),
                    },
                ),
            ),
            "assembly": (
                "struct",
                {
                    "name": "s",
                    "culture": "s",
                    "version": (
                        "struct",
                        {
                            "major": "i",
                            "minor": "i",
                            "build_number": "i",
                            "revision_number": "i",
                        },
                    ),
                },
            ),
            "assembly_refs": (
                "array",
                (
                    "struct",
                    {
                        "name": "s",
                        "version": (
                            "struct",
                            {
                                "major": "i",
                                "minor": "i",
                                "build_number": "i",
                                "revision_number": "i",
                            },
                        ),
                        "public_key_or_token": "s",
                    },
                ),
            ),
            "resources": (
                "array",
                (
                    "struct",
                    {
                        "name": "s",
                        "offset": "i",
                        "length": "i",
                    },
                ),
            ),
            "streams": (
                "array",
                (
                    "struct",
                    {
                        "name": "s",
                        "offset": "i",
                        "size": "i",
                    },
                ),
            ),
            "guids": ("array", "s"),
            "user_strings": ("array", "s"),
        },
    },
    "time": {"funcs": {"now": ("i", [])}},
    "console": {
        "funcs": {
            "log": ("b", [("message", "scalar"), ("value", "scalar")], 1),
            "hex": ("b", [("value", "i")]),
        }
    },
    "string": {
        "funcs": {
            "to_int": ("i", [("s", "s"), ("base", "i")], 1),
            "length": ("i", [("s", "s")]),
        },
    },
    "cuckoo": {
        "attrs": {
            "network": ("struct", {}),
            "filesystem": ("struct", {}),
            "registry": ("struct", {}),
            "sync": ("struct", {}),
        },
        "funcs": {
            "network.http_request": ("b", [("regexp", "r")]),
            "network.http_get": ("b", [("regexp", "r")]),
            "network.http_post": ("b", [("regexp", "r")]),
            "network.http_user_agent": ("b", [("regexp", "r")]),
            "network.dns_lookup": ("b", [("regexp", "r")]),
            "network.host": ("b", [("regexp", "r")]),
            "network.tcp": ("b", [("regexp", "r"), ("port", "i")]),
            "network.udp": ("b", [("regexp", "r"), ("port", "i")]),
            "registry.key_access": ("b", [("regexp", "r")]),
            "filesystem.file_access": ("b", [("regexp", "r")]),
            "sync.mutex": ("b", [("regexp", "r")]),
        },
    },
    "vt": {"attrs": {"metadata": ("struct", {})}},
}


def _resolve_type(spec: Any) -> YaraType:
    """Map a type spec to an actual YaraType instance."""
    from yaraast.types._registry_collections import ArrayType, DictionaryType, StructType
    from yaraast.types._registry_primitives import (
        AnyType,
        BooleanType,
        DoubleType,
        IntegerType,
        RegexType,
        ScalarType,
        StringType,
    )

    primitives: dict[str, YaraType] = {
        "i": IntegerType(),
        "s": StringType(),
        "b": BooleanType(),
        "d": DoubleType(),
        "r": RegexType(),
        "scalar": ScalarType(),
    }
    if isinstance(spec, str):
        return primitives.get(spec, AnyType())
    if not isinstance(spec, tuple) or not spec:
        return AnyType()
    tag = spec[0]
    if tag == "array":
        return ArrayType(_resolve_type(spec[1]))
    if tag == "dict":
        return DictionaryType(_resolve_type(spec[1]), _resolve_type(spec[2]))
    if tag == "struct":
        return StructType({k: _resolve_type(v) for k, v in spec[1].items()})
    return IntegerType()


def load_builtin_modules() -> dict[str, ModuleDefinition]:
    """Create builtin module definitions from declarative specs."""
    modules: dict[str, ModuleDefinition] = {}
    for name, spec in _MODULE_SPECS.items():
        mod = ModuleDefinition(name=name)
        if "consts" in spec:
            mod.constants = {k: _resolve_type(v) for k, v in spec["consts"].items()}
        if "attrs" in spec:
            mod.attributes = {k: _resolve_type(v) for k, v in spec["attrs"].items()}
        if mod.constants:
            mod.attributes.update(mod.constants)
        if "funcs" in spec:
            mod.functions = {
                fname: FunctionDefinition(
                    fname,
                    _resolve_type(fspec[0]),
                    [(p[0], _resolve_type(p[1])) for p in fspec[1]],
                    fspec[2] if len(fspec) > 2 else None,
                    fspec[3] if len(fspec) > 3 else False,
                )
                for fname, fspec in spec["funcs"].items()
            }
        modules[name] = mod
    return modules
