"""Protocols shared by lexer helper modules."""

from __future__ import annotations

from typing import Protocol

from yaraast.lexer.tokens import Token, TokenType


class LexerLike(Protocol):
    """Structural contract required by lexer helper functions."""

    KEYWORDS: dict[str, TokenType]
    text: str
    position: int
    line: int
    column: int
    tokens: list[Token]

    def _current_char(self) -> str | None: ...

    def _peek_char(self, offset: int = 1) -> str | None: ...

    def _advance(self) -> None: ...

    def _is_line_continuation(self) -> bool: ...

    def _is_regex_context(self) -> bool: ...

    def _is_hex_string_context(self) -> bool: ...

    def _read_string(self) -> Token: ...

    def _read_hex_string(self) -> Token: ...

    def _read_regex(self) -> Token: ...

    def _read_number(self) -> Token: ...

    def _read_identifier(self) -> Token: ...

    def _read_string_identifier(self) -> Token: ...

    def _read_string_count(self) -> Token: ...

    def _read_string_offset(self) -> Token: ...

    def _read_string_length(self) -> Token: ...
