"""Version information for YARAAST."""

# YARAAST version
YARAAST_VERSION_MAJOR = 2
YARAAST_VERSION_MINOR = 0
YARAAST_VERSION_PATCH = 0
YARAAST_VERSION = f"{YARAAST_VERSION_MAJOR}.{YARAAST_VERSION_MINOR}.{YARAAST_VERSION_PATCH}"

# YARA syntax version we're compatible with
YARA_SYNTAX_VERSION = "4.5.0"
YARAX_SYNTAX_VERSION = "0.4.0"
