"""Version information for YARAAST."""

# YARAAST version
YARAAST_VERSION_MAJOR = 1
YARAAST_VERSION_MINOR = 0
YARAAST_VERSION_PATCH = 1
YARAAST_VERSION = f"{YARAAST_VERSION_MAJOR}.{YARAAST_VERSION_MINOR}.{YARAAST_VERSION_PATCH}"

# YARA syntax version we're compatible with
YARA_SYNTAX_VERSION = "4.5.0"
YARA_SYNTAX_VERSION_MAJOR = 4
YARA_SYNTAX_VERSION_MINOR = 5
YARA_SYNTAX_VERSION_PATCH = 0

# YARA-X compatibility version
YARAX_SYNTAX_VERSION = "0.4.0"

# Build information
BUILD_DATE = "2024-01-01"
BUILD_COMMIT = "unknown"
