"""Shared type contract for enhanced YARA-L parser mixins."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from yaraast.lexer.tokens import TokenType as BaseTokenType

from .lexer import YaraLToken
from .tokens import YaraLTokenType


class EnhancedParserMixinBase:
    """Declare state and methods supplied by the complete enhanced parser."""

    if TYPE_CHECKING:
        tokens: list[YaraLToken]
        current: int

        def _check_keyword(self, keyword: str) -> bool: ...

        def _consume_keyword(self, keyword: str) -> YaraLToken: ...

        def _check_yaral_type(self, token_type: YaraLTokenType) -> bool: ...

        def _check_section_keyword(self) -> bool: ...

        def _peek(self) -> YaraLToken: ...

        def _peek_ahead(self, count: int) -> YaraLToken | None: ...

        def _advance(self) -> YaraLToken: ...

        def _check(self, token_type: BaseTokenType) -> bool: ...

        def _consume(self, token_type: BaseTokenType, message: str) -> YaraLToken: ...

        def _is_at_end(self) -> bool: ...

        def _error(self, message: str) -> Exception: ...

        def _parse_event_value(self) -> Any: ...

        def _parse_udm_field_access(self) -> Any: ...

        def _parse_udm_field_path(self) -> Any: ...

        def _parse_regex_pattern(self) -> Any: ...

        def _parse_condition_expression(self) -> Any: ...

        def _parse_conditional_expression(self) -> Any: ...

        def _parse_comparison_operator(self) -> str: ...

        def _parse_events_section(self) -> Any: ...

        def _parse_match_section(self) -> Any: ...

        def _parse_condition_section(self) -> Any: ...

        def _parse_outcome_section(self) -> Any: ...

        def _parse_duration_parts(self) -> Any: ...

        def _format_event_value_text(self, value: Any) -> str: ...

        def _format_condition_expression_text(self, value: Any) -> str: ...

        def _check_event_arithmetic_operator(self) -> bool: ...

        def _parse_event_arithmetic_text(self, left: str) -> str: ...

        def _is_event_function_call_value_start(self) -> bool: ...
